language: node_js

git:
  depth: 3

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      name: "Deploy to gh-pages"
      if: branch = master
      script:
        - mkdir gh-pages
        - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/aria/master/index.html -o gh-pages/index.html -f  --retry 3
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: gh-pages
        on:
          branch: master
